required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: -188.480
  y: 64.0
  z: 25.420
  yaw: 88.4
  pitch: 37.8
arenas:
  0:
    world: 'world'
    x: -194.360
    y: 64.0
    z: 26.548
    yaw: 90.2
    pitch: 13.2
  1:
    world: 'world'
    x: -194.566
    y: 64.0
    z: 33.345
    yaw: 88.5
    pitch: 6.1